#!/usr/bin/bash -ex

mkdir -p .gear
cp -a build-aux/altlinux/rules ./.gear/

version=$(./build-aux/get_meson_version)
release=0.$(date +%s)

sed -e "s/@VERSION@/${version}/g" \
    -e "s/@RELEASE@/${release}/g" \
    build-aux/altlinux/alt-software.spec.in > alt-software.spec

add_changelog alt-software.spec -e '- Regular build.'
