name: CI Pull Request

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  APP_ID: com.example.SuperDev2007.SomeApp
  DEVELOPER_NAME: SuperDev2007
  DEVELOPER_EMAIL: <super.dev-2007@master.dev>

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lint
      run: io.elementary.vala-lint -d .

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs: lint

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests and lint
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: atomic-control-center.flatpak
        manifest-path: build-aux/flatpak/org.altlinux.AtomicControlCenter.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }} 
